# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KcAgent < Formula
  desc "Local agent for KubeStellar Console - bridges browser to kubeconfig and Claude Code"
  homepage "https://github.com/kubestellar/console"
  version "0.3.11-nightly.20260219"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kubestellar/console/releases/download/v0.3.11-nightly.20260219/kc-agent_0.3.11-nightly.20260219_darwin_amd64.tar.gz"
      sha256 "f9b8c40a5bde22ebc604f9dc15e18d75d8d20422bb7f4ed5d0b1c3746f9bea2f"

      def install
        bin.install "kc-agent"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kubestellar/console/releases/download/v0.3.11-nightly.20260219/kc-agent_0.3.11-nightly.20260219_darwin_arm64.tar.gz"
      sha256 "b35af0563cbc5e1a7e15368cbccf44597e6822c73691a925522de1386d3c3df5"

      def install
        bin.install "kc-agent"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kubestellar/console/releases/download/v0.3.11-nightly.20260219/kc-agent_0.3.11-nightly.20260219_linux_amd64.tar.gz"
      sha256 "2e5b041a72acdf4b5c4eaaaad8135aa35f4a82c8cbcb72b9cccd9ddf4b66fd28"
      def install
        bin.install "kc-agent"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kubestellar/console/releases/download/v0.3.11-nightly.20260219/kc-agent_0.3.11-nightly.20260219_linux_arm64.tar.gz"
      sha256 "021855840a493521e09843df3311e621ad0b3b7f4fdbee7920b6ae93931be254"
      def install
        bin.install "kc-agent"
      end
    end
  end

  test do
    system "#{bin}/kc-agent", "--version"
  end
end
