# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KcAgent < Formula
  desc "Local agent for KubeStellar Console - bridges browser to kubeconfig and Claude Code"
  homepage "https://github.com/kubestellar/console"
  version "0.3.10-nightly.20260212"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kubestellar/console/releases/download/v0.3.10-nightly.20260212/kc-agent_0.3.10-nightly.20260212_darwin_amd64.tar.gz"
      sha256 "9d96d077b32a772b342dcf924d916411b22a48b1a07cb774c21d6587119643ca"

      def install
        bin.install "kc-agent"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kubestellar/console/releases/download/v0.3.10-nightly.20260212/kc-agent_0.3.10-nightly.20260212_darwin_arm64.tar.gz"
      sha256 "38e9b1262e8cc66e5a46607d0f5fcf6db3962a39a423500d9b4e8a81c47c199e"

      def install
        bin.install "kc-agent"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kubestellar/console/releases/download/v0.3.10-nightly.20260212/kc-agent_0.3.10-nightly.20260212_linux_amd64.tar.gz"
      sha256 "7900524affc3c4ecf2447fd2dea15d9bf4ff1f74055da21608463cb9243f96ab"
      def install
        bin.install "kc-agent"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kubestellar/console/releases/download/v0.3.10-nightly.20260212/kc-agent_0.3.10-nightly.20260212_linux_arm64.tar.gz"
      sha256 "1ff9aa4b8f906a919bd7720b99c3f1eb0a2ac26f3084b5e2a25a674b503dc56e"
      def install
        bin.install "kc-agent"
      end
    end
  end

  test do
    system "#{bin}/kc-agent", "--version"
  end
end
