# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KkcAgent < Formula
  desc "Local agent for KubeStellar Klaude Console - bridges browser to kubeconfig and Claude Code"
  homepage "https://github.com/kubestellar/console"
  version "0.3.6-nightly.20260124"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kubestellar/console/releases/download/v0.3.6-nightly.20260124/kkc-agent_0.3.6-nightly.20260124_darwin_amd64.tar.gz"
      sha256 "46e773a9434350fa2c10b6de7c8e9cae3825bbe9eb63861469310b9e393c3cf5"

      def install
        bin.install "kkc-agent"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kubestellar/console/releases/download/v0.3.6-nightly.20260124/kkc-agent_0.3.6-nightly.20260124_darwin_arm64.tar.gz"
      sha256 "d93525c9342ed476de44062bd7d16a45c0ef384efa42803c99248015d528cc6c"

      def install
        bin.install "kkc-agent"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kubestellar/console/releases/download/v0.3.6-nightly.20260124/kkc-agent_0.3.6-nightly.20260124_linux_amd64.tar.gz"
      sha256 "06091d8dbd8acb1a53948c323bb68fed2a45de8e25b420b468ba5375accf431e"
      def install
        bin.install "kkc-agent"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kubestellar/console/releases/download/v0.3.6-nightly.20260124/kkc-agent_0.3.6-nightly.20260124_linux_arm64.tar.gz"
      sha256 "5d4bf1936ff832675f5872856002dd03a6e13c253b8db0a4e17b5c60c093db47"
      def install
        bin.install "kkc-agent"
      end
    end
  end

  test do
    system "#{bin}/kkc-agent", "--version"
  end
end
