# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KlaudeDeploy < Formula
  desc "App-centric multi-cluster deployment and operations for Kubernetes"
  homepage "https://github.com/kubestellar/klaude"
  version "0.8.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kubestellar/klaude/releases/download/v0.8.0/klaude-deploy_0.8.0_darwin_amd64.tar.gz"
      sha256 "47cfeb85dd0047a2020fd390fcc97aaa82ff2d97577ce826ebfceee95f9e4374"

      def install
        bin.install "klaude-deploy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kubestellar/klaude/releases/download/v0.8.0/klaude-deploy_0.8.0_darwin_arm64.tar.gz"
      sha256 "1dfdfffa2f118cd194057ffb8de6a3603c51c8a706a68cf67dd4ac568d81be2c"

      def install
        bin.install "klaude-deploy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kubestellar/klaude/releases/download/v0.8.0/klaude-deploy_0.8.0_linux_amd64.tar.gz"
      sha256 "026e1dd102c9a61cf74d08fd3d0b4fdae67d8e1ffdc092d46c36adb8566aa29e"
      def install
        bin.install "klaude-deploy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kubestellar/klaude/releases/download/v0.8.0/klaude-deploy_0.8.0_linux_arm64.tar.gz"
      sha256 "5c528fc2520277297573d386ce1bae0dcddfcacf73223bc66c361250b14557ab"
      def install
        bin.install "klaude-deploy"
      end
    end
  end

  test do
    system "#{bin}/klaude-deploy", "version"
  end
end
