# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KlaudeDeploy < Formula
  desc "App-centric multi-cluster deployment and operations for Kubernetes"
  homepage "https://github.com/kubestellar/klaude"
  version "0.8.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kubestellar/klaude/releases/download/v0.8.1/klaude-deploy_0.8.1_darwin_amd64.tar.gz"
      sha256 "8e6ce9507014951e5b9b583fe2a8f9c94f2d86be93c8a73ba94d82cd62b659a7"

      def install
        bin.install "klaude-deploy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kubestellar/klaude/releases/download/v0.8.1/klaude-deploy_0.8.1_darwin_arm64.tar.gz"
      sha256 "553b6640c572d9dbe18c659eb7277ee7ed5926ed472ffe085a34b44dad607773"

      def install
        bin.install "klaude-deploy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kubestellar/klaude/releases/download/v0.8.1/klaude-deploy_0.8.1_linux_amd64.tar.gz"
      sha256 "6562f9794b2a7e0087c4e9601b28033247d17324c2182b0a49f1120f5fb62d16"
      def install
        bin.install "klaude-deploy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kubestellar/klaude/releases/download/v0.8.1/klaude-deploy_0.8.1_linux_arm64.tar.gz"
      sha256 "920ea1edf4b40b0b40a5d6f62924e7fcd5765a7a7c267c14bfff108c58cd0294"
      def install
        bin.install "klaude-deploy"
      end
    end
  end

  test do
    system "#{bin}/klaude-deploy", "version"
  end
end
