# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Klaude < Formula
  desc "AI-powered multi-cluster Kubernetes management for Claude Code"
  homepage "https://github.com/kubestellar/klaude"
  version "0.6.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kubestellar/klaude/releases/download/v0.6.0/klaude_0.6.0_darwin_amd64.tar.gz"
      sha256 "4220da5cff3a607acd4865dfee67f4147e0cb2bc0a7b72bc420069f6a2851e8f"

      def install
        bin.install "klaude"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kubestellar/klaude/releases/download/v0.6.0/klaude_0.6.0_darwin_arm64.tar.gz"
      sha256 "c6ee02717f6f964d1cbdb1192df38e7bc3619f67ea010acc07d0de57ec5b0cba"

      def install
        bin.install "klaude"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kubestellar/klaude/releases/download/v0.6.0/klaude_0.6.0_linux_amd64.tar.gz"
      sha256 "75adc1829c99765b1ea74de2719fcc239fcc35dec0991c599652d4c66415ca0f"
      def install
        bin.install "klaude"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kubestellar/klaude/releases/download/v0.6.0/klaude_0.6.0_linux_arm64.tar.gz"
      sha256 "868b6dbd7634b1500178760aa11b59981eef70c30b6f9b8568e487e697b7ccf9"
      def install
        bin.install "klaude"
      end
    end
  end

  test do
    system "#{bin}/klaude", "version"
  end
end
