# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KlaudeOps < Formula
  desc "Multi-cluster Kubernetes diagnostics, RBAC analysis, and security checks"
  homepage "https://github.com/kubestellar/klaude"
  version "0.8.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kubestellar/klaude/releases/download/v0.8.0/klaude-ops_0.8.0_darwin_amd64.tar.gz"
      sha256 "b592d6c53aa0b02db1a53a6d9955ab20cec209921f91180ccba7779a4c1a2aec"

      def install
        bin.install "klaude-ops"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kubestellar/klaude/releases/download/v0.8.0/klaude-ops_0.8.0_darwin_arm64.tar.gz"
      sha256 "944ebe78853c749135c65f50985ba55d773ac7c432084e1d959a28be65d4a41c"

      def install
        bin.install "klaude-ops"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kubestellar/klaude/releases/download/v0.8.0/klaude-ops_0.8.0_linux_amd64.tar.gz"
      sha256 "9c5968c537706e55536c31d0322ebbf96c638852edc9331741815e57ee29379f"
      def install
        bin.install "klaude-ops"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kubestellar/klaude/releases/download/v0.8.0/klaude-ops_0.8.0_linux_arm64.tar.gz"
      sha256 "776cb10ab5ac30540772f6d84088509210e384b155f6557303187ce10f5b40ac"
      def install
        bin.install "klaude-ops"
      end
    end
  end

  test do
    system "#{bin}/klaude-ops", "version"
  end
end
