# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KlaudeDeploy < Formula
  desc "App-centric multi-cluster deployment and operations for Kubernetes"
  homepage "https://github.com/kubestellar/klaude"
  version "0.7.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kubestellar/klaude/releases/download/v0.7.0/klaude-deploy_0.7.0_darwin_amd64.tar.gz"
      sha256 "246be900b12c70943bb9a6f10af2095d5c4d66db1d66caaa90388e8260860d51"

      def install
        bin.install "klaude-deploy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kubestellar/klaude/releases/download/v0.7.0/klaude-deploy_0.7.0_darwin_arm64.tar.gz"
      sha256 "6a56096127db2ec4c442f68766d6a6c33616c6fb166aa81dcbb57d945031c9c8"

      def install
        bin.install "klaude-deploy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kubestellar/klaude/releases/download/v0.7.0/klaude-deploy_0.7.0_linux_amd64.tar.gz"
      sha256 "98dc357e29526240384416ef0576a6258f31468bc5fba50e9518b82a5e3195f4"
      def install
        bin.install "klaude-deploy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kubestellar/klaude/releases/download/v0.7.0/klaude-deploy_0.7.0_linux_arm64.tar.gz"
      sha256 "e67d08df82538a50c7d8ec127a92c665b767f6dfe9997dfd369e3c7c637f484a"
      def install
        bin.install "klaude-deploy"
      end
    end
  end

  test do
    system "#{bin}/klaude-deploy", "version"
  end
end
