# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubectlClaude < Formula
  desc "AI-powered multi-cluster Kubernetes management for Claude Code"
  homepage "https://github.com/kubestellar/kubectl-claude"
  version "0.3.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kubestellar/kubectl-claude/releases/download/v0.3.1/kubectl-claude_0.3.1_darwin_amd64.tar.gz"
      sha256 "7fdda7c486108d95230060aca13c7eed4974e1dee963a5a446ddc0563d1b0a33"

      def install
        bin.install "kubectl-claude"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kubestellar/kubectl-claude/releases/download/v0.3.1/kubectl-claude_0.3.1_darwin_arm64.tar.gz"
      sha256 "446840abc6ac16ae35e210a09389fa90a8f0594d9e78373fce39669982b1524c"

      def install
        bin.install "kubectl-claude"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kubestellar/kubectl-claude/releases/download/v0.3.1/kubectl-claude_0.3.1_linux_amd64.tar.gz"
      sha256 "3f47a52705b29037386bb5d71f014bd936a376f63b1e0b58c0bcc44c2ecd3058"
      def install
        bin.install "kubectl-claude"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kubestellar/kubectl-claude/releases/download/v0.3.1/kubectl-claude_0.3.1_linux_arm64.tar.gz"
      sha256 "f4631a085f1fba4416f97a4808d0f87edf83861db158b8aa707d29d5d225a510"
      def install
        bin.install "kubectl-claude"
      end
    end
  end

  test do
    system "#{bin}/kubectl-claude", "version"
  end
end
