# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubestellarDeploy < Formula
  desc "App-centric multi-cluster deployment and operations for Kubernetes"
  homepage "https://github.com/kubestellar/kubestellar-mcp"
  version "0.8.4"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kubestellar/kubestellar-mcp/releases/download/v0.8.4/kubestellar-deploy_0.8.4_darwin_amd64.tar.gz"
      sha256 "1eac63d26cf62de8a34dc91e939ceff7209c378fa7060603ef9ebd8b40abd180"

      def install
        bin.install "kubestellar-deploy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kubestellar/kubestellar-mcp/releases/download/v0.8.4/kubestellar-deploy_0.8.4_darwin_arm64.tar.gz"
      sha256 "1836c8d49d65d56c5ed7d9c1b97f728245a9d7940252ae03ce82ad43bd8399a4"

      def install
        bin.install "kubestellar-deploy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kubestellar/kubestellar-mcp/releases/download/v0.8.4/kubestellar-deploy_0.8.4_linux_amd64.tar.gz"
      sha256 "a1e1bde9caed9e300548ce9e04c19b5d2a00481ef4a76f5a96b30e0c0e8c8b92"
      def install
        bin.install "kubestellar-deploy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kubestellar/kubestellar-mcp/releases/download/v0.8.4/kubestellar-deploy_0.8.4_linux_arm64.tar.gz"
      sha256 "c16709f1adb2f58a312fcb953be2be1e6e1c735061ed17f57f54588d7585ae91"
      def install
        bin.install "kubestellar-deploy"
      end
    end
  end

  test do
    system "#{bin}/kubestellar-deploy", "version"
  end
end
