# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubestellarOps < Formula
  desc "Multi-cluster Kubernetes diagnostics, RBAC analysis, and security checks"
  homepage "https://github.com/kubestellar/kubestellar-mcp"
  version "0.9.11"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kubestellar/kubestellar-mcp/releases/download/v0.9.11/kubestellar-ops_0.9.11_darwin_amd64.tar.gz"
      sha256 "fddcd76c7b13f290d46c9dd71a7844c93fb4a865f5484f6d89433a4f77bcc776"

      define_method(:install) do
        bin.install "kubestellar-ops"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kubestellar/kubestellar-mcp/releases/download/v0.9.11/kubestellar-ops_0.9.11_darwin_arm64.tar.gz"
      sha256 "90cede631dd3b2be8cdaa167f3dde8582bc0524a221126b5d125c9fcec722c83"

      define_method(:install) do
        bin.install "kubestellar-ops"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kubestellar/kubestellar-mcp/releases/download/v0.9.11/kubestellar-ops_0.9.11_linux_amd64.tar.gz"
      sha256 "f720aca6635885b8746572999d2aee1efbc8876f0163a3d307f4e9656f5aff3a"
      define_method(:install) do
        bin.install "kubestellar-ops"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kubestellar/kubestellar-mcp/releases/download/v0.9.11/kubestellar-ops_0.9.11_linux_arm64.tar.gz"
      sha256 "922cf207b24ec6568b99eaf40c49843f040bc832ccc3b0177c4eeb5da3487b00"
      define_method(:install) do
        bin.install "kubestellar-ops"
      end
    end
  end

  test do
    system bin/"kubestellar-ops", "version"
  end
end
