# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubestellarDeploy < Formula
  desc "App-centric multi-cluster deployment and operations for Kubernetes"
  homepage "https://github.com/kubestellar/kubestellar-mcp"
  version "0.8.11"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kubestellar/kubestellar-mcp/releases/download/v0.8.11/kubestellar-deploy_0.8.11_darwin_amd64.tar.gz"
      sha256 "057a48f15e9e451ad91e3c5d8519edb90a583938282c02e5a5d21dd1ffd4c807"

      define_method(:install) do
        bin.install "kubestellar-deploy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kubestellar/kubestellar-mcp/releases/download/v0.8.11/kubestellar-deploy_0.8.11_darwin_arm64.tar.gz"
      sha256 "64d95344fa2757fb2b7a6d9ae5e7ab95fdbacb5dffae2c9dbbef01086d720f55"

      define_method(:install) do
        bin.install "kubestellar-deploy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kubestellar/kubestellar-mcp/releases/download/v0.8.11/kubestellar-deploy_0.8.11_linux_amd64.tar.gz"
      sha256 "c31e1d9370c43ba9f765cd2278d12d9be851e9efe0194160e77e1de7e28bde7a"
      define_method(:install) do
        bin.install "kubestellar-deploy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kubestellar/kubestellar-mcp/releases/download/v0.8.11/kubestellar-deploy_0.8.11_linux_arm64.tar.gz"
      sha256 "4383c240860d6e7b22c3299576889ecb905fff1935c413661c49454faa429125"
      define_method(:install) do
        bin.install "kubestellar-deploy"
      end
    end
  end

  test do
    system "#{bin}/kubestellar-deploy", "version"
  end
end
