#!/usr/bin/env python3
"""Additional codegen-drift invariants for Formula/*.rb.

The existing test modules already lock in magic comments, class name,
version-in-URL, HTTPS/GitHub URLs, sha256 hex shape, the
`define_method(:install)` form, the `on_macos`/`on_linux` block layout,
description/homepage audit rules, and the release-artifact tuple.

This module targets a further class of GoReleaser-template drift that
would still pass `brew audit` but silently corrupt the tap:

  * Every formula includes the "DO NOT EDIT" marker comment that
    GoReleaser emits. Dropping it removes the human warning that
    hand-edits will be clobbered on the next release, and lets subtle
    drift accumulate under review.
  * The homepage repository is exactly the same GitHub owner/repo used
    by every one of the formula's release URLs. A drift here means the
    tap points users at a moved/archived repo while still downloading
    binaries from the correct one — or vice versa.
  * The four `if Hardware::CPU.*` blocks are emitted in a canonical
    order (darwin-intel, darwin-arm, linux-intel, linux-arm). The
    ordering is what makes the codegen output stable across runs and
    reviewable via `git diff`; a template rewrite that shuffled them
    would produce a huge no-op diff on the next nightly and mask real
    changes.
  * Every formula's `test do` block uses `system` (not `shell_output`
    or a pure Ruby assertion). GoReleaser's default is `system` for
    all four tap formulae; a divergence signals a manual edit.
  * The version string only appears at the top-level `version` line
    and inside URLs. It never appears in `desc`, `homepage`, or any
    other formula field — that would embed a version in metadata that
    is otherwise version-agnostic and cause churn on every bump.
"""

import re
import unittest
from pathlib import Path

FORMULA_DIR = Path(__file__).resolve().parent.parent / "Formula"

DO_NOT_EDIT_RE = re.compile(
    r"#\s*This file was generated by GoReleaser\.\s*DO NOT EDIT\.",
    re.IGNORECASE,
)

URL_LINE_RE = re.compile(r'url\s+"([^"]+)"')
HOMEPAGE_RE = re.compile(r'^\s*homepage\s+"([^"]+)"', re.MULTILINE)
VERSION_RE = re.compile(r'^\s*version\s+"([^"]+)"', re.MULTILINE)
DESC_RE = re.compile(r'^\s*desc\s+"([^"]+)"', re.MULTILINE)
IF_HW_RE = re.compile(r'^\s*if Hardware::CPU\.(\w+)(?:\s+&&\s+Hardware::CPU\.(\w+))?\s+do?', re.MULTILINE)
IF_HW_ANY_RE = re.compile(r'^\s*if Hardware::CPU\.[^\n]*', re.MULTILINE)
TEST_BLOCK_RE = re.compile(r'\btest\s+do\b([\s\S]*?)\bend\b', re.MULTILINE)

GITHUB_REPO_URL_RE = re.compile(r'^https://github\.com/([^/]+)/([^/]+)(?:/|$)')

CANONICAL_BLOCK_ORDER = [
    "darwin_amd64",
    "darwin_arm64",
    "linux_amd64",
    "linux_arm64",
]


def _load_formulae():
    files = sorted(FORMULA_DIR.glob("*.rb"))
    if not files:
        raise AssertionError(f"no formulae found under {FORMULA_DIR}")
    return {p.stem: p.read_text() for p in files}


def _github_owner_repo(url: str):
    """Return (owner, repo) if url is https://github.com/owner/repo[/...], else None."""
    m = GITHUB_REPO_URL_RE.match(url)
    if not m:
        return None
    return m.group(1), m.group(2)


def _platform_tuples_in_order(text: str):
    """For each release URL in file order, return its trailing
    `<os>_<arch>` tuple derived from the filename in the URL path.

    URLs look like:
      .../releases/download/vX.Y.Z/<name>_<version>_<os>_<arch>.tar.gz

    Returns a list of "os_arch" strings in the order the URLs appear.
    """
    tuples = []
    for url in URL_LINE_RE.findall(text):
        tail = url.rsplit("/", 1)[-1]
        # <name>_<version>_<os>_<arch>.tar.gz — the last two "_"-separated
        # tokens before .tar.gz are the platform tuple.
        base = tail[:-len(".tar.gz")] if tail.endswith(".tar.gz") else tail
        parts = base.split("_")
        if len(parts) < 2:
            continue
        tuples.append(f"{parts[-2]}_{parts[-1]}")
    return tuples


class FormulaFurtherCodegenInvariants(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.formulae = _load_formulae()

    def test_every_formula_carries_the_do_not_edit_marker(self):
        """GoReleaser emits `# This file was generated by GoReleaser. DO NOT EDIT.`
        as a warning to anyone reading the source. Removing it lets
        hand-edits accumulate under review because the human reader has
        no signal that the file is templated."""
        for name, text in self.formulae.items():
            with self.subTest(formula=name):
                self.assertRegex(
                    text, DO_NOT_EDIT_RE,
                    f"{name}.rb is missing the GoReleaser "
                    f"'DO NOT EDIT' marker comment",
                )

    def test_homepage_repo_matches_release_url_repo(self):
        """The homepage GitHub owner/repo must be the same as the owner/repo
        that appears in every release URL. A mismatch means the tap
        points users at a moved or archived repo while still downloading
        binaries from a different one — the classic 'we forgot to
        update homepage after the migration' bug."""
        for name, text in self.formulae.items():
            with self.subTest(formula=name):
                hp = HOMEPAGE_RE.search(text)
                self.assertIsNotNone(hp, f"{name}.rb has no homepage line")
                hp_repo = _github_owner_repo(hp.group(1))
                self.assertIsNotNone(
                    hp_repo,
                    f"{name}.rb homepage is not a github.com/owner/repo URL: {hp.group(1)}",
                )
                for url in URL_LINE_RE.findall(text):
                    with self.subTest(url=url):
                        url_repo = _github_owner_repo(url)
                        self.assertIsNotNone(
                            url_repo,
                            f"{name}.rb release URL is not github.com/owner/repo: {url}",
                        )
                        self.assertEqual(
                            url_repo, hp_repo,
                            f"{name}.rb homepage repo {hp_repo} != release URL repo "
                            f"{url_repo} (url: {url})",
                        )

    def test_platform_blocks_appear_in_canonical_order(self):
        """The four platform URLs must appear in the canonical order:
        darwin_amd64, darwin_arm64, linux_amd64, linux_arm64. This order
        is what makes the codegen output stable across nightly runs and
        keeps `git diff` reviewable; a template rewrite that reshuffled
        them would produce huge no-op diffs on every release that would
        mask real changes."""
        for name, text in self.formulae.items():
            with self.subTest(formula=name):
                observed = _platform_tuples_in_order(text)
                self.assertEqual(
                    observed, CANONICAL_BLOCK_ORDER,
                    f"{name}.rb platform blocks are not in canonical order: "
                    f"got {observed}, want {CANONICAL_BLOCK_ORDER}",
                )

    def test_test_block_uses_system_form(self):
        """Every `test do` block invokes `system` (the GoReleaser default).
        A divergence — e.g. someone hand-editing to `shell_output(...)`
        or a pure Ruby assertion — is a smell that the file was edited
        outside the codegen path and will be clobbered next release."""
        for name, text in self.formulae.items():
            with self.subTest(formula=name):
                m = TEST_BLOCK_RE.search(text)
                self.assertIsNotNone(m, f"{name}.rb has no test do block")
                body = m.group(1)
                self.assertIn(
                    "system", body,
                    f"{name}.rb test block does not use system(...): {body!r}",
                )
                # And must not use shell_output — that's an audit rule
                # violation and a strong signal of a hand-edit.
                self.assertNotIn(
                    "shell_output", body,
                    f"{name}.rb test block uses shell_output — likely a "
                    f"hand-edit that will be clobbered by the next release",
                )

    def test_version_string_does_not_leak_into_desc_or_homepage(self):
        """The declared version must appear only on the `version` line
        and inside URLs. If it leaked into `desc` or `homepage`, every
        nightly bump would rewrite those lines — masking real edits and
        churning the codegen diff. This test guards against that."""
        for name, text in self.formulae.items():
            with self.subTest(formula=name):
                v = VERSION_RE.search(text)
                self.assertIsNotNone(v, f"{name}.rb has no version line")
                ver = v.group(1)

                desc = DESC_RE.search(text)
                if desc:
                    self.assertNotIn(
                        ver, desc.group(1),
                        f"{name}.rb description embeds version {ver!r}: "
                        f"{desc.group(1)!r}",
                    )
                hp = HOMEPAGE_RE.search(text)
                if hp:
                    self.assertNotIn(
                        ver, hp.group(1),
                        f"{name}.rb homepage embeds version {ver!r}: "
                        f"{hp.group(1)!r}",
                    )


if __name__ == "__main__":
    unittest.main()
