"""Codegen invariants for the per-platform ``if Hardware::CPU.*`` guard
predicates inside each Formula.

Every formula in ``Formula/`` is generated by GoReleaser and lays out
four hardware-guarded install slots, two under ``on_macos do`` and two
under ``on_linux do``. The exact guard predicate on each slot is not
cosmetic:

* Linux slots MUST additionally gate on ``Hardware::CPU.is_64_bit?``.
  We only publish ``linux_amd64`` and ``linux_arm64`` tarballs; without
  the ``is_64_bit?`` guard, a Homebrew-on-Linux install on i686 or
  armv7 would match ``Hardware::CPU.intel?`` / ``Hardware::CPU.arm?``
  and try to run a 64-bit binary, which fails with a confusing loader
  error rather than a clean "no bottle for your platform" message.

* macOS slots MUST NOT gate on ``is_64_bit?``. Apple dropped 32-bit
  userland at macOS Catalina, so the guard is dead code. Its presence
  is a strong smell that the file was hand-edited outside the codegen
  path (or that the template diverged), which will silently clobber
  on the next nightly release and mask the real regression.

These invariants are already implied by the tarball naming
convention checked in ``test_crossformula_invariants``, but they
guard the Ruby *predicate* itself — a codegen shuffle that swapped
guard clauses while leaving URLs intact would slip past the existing
tarball-suffix checks and only surface as a broken ``brew install``.
"""

import re
import unittest
from pathlib import Path

FORMULA_DIR = Path(__file__).resolve().parent.parent / "Formula"

ON_MACOS_RE = re.compile(r"^\s*on_macos\s+do\b")
ON_LINUX_RE = re.compile(r"^\s*on_linux\s+do\b")
END_RE = re.compile(r"^\s*end\s*$")
HARDWARE_IF_RE = re.compile(r"^\s*if\s+Hardware::CPU\.(intel|arm)\?")


def _load_formulae():
    files = sorted(FORMULA_DIR.glob("*.rb"))
    return {p.stem: p.read_text() for p in files}


def _guard_lines_by_os(text):
    """Yield (os_name, guard_line) for each ``if Hardware::CPU.(intel|arm)?``
    line inside an ``on_macos do`` / ``on_linux do`` block.

    A tiny brace/indent tracker suffices because the generated files
    never nest ``on_*`` blocks and use two-space indentation.
    """
    os_stack = []
    # depth of the currently-open on_* block, counted in `end` lines
    # we still need to close before it exits.
    depth = 0
    for raw in text.splitlines():
        if os_stack and END_RE.match(raw):
            depth -= 1
            if depth == 0:
                os_stack.pop()
            continue
        if ON_MACOS_RE.match(raw):
            os_stack.append("macos")
            depth = 1
            continue
        if ON_LINUX_RE.match(raw):
            os_stack.append("linux")
            depth = 1
            continue
        if os_stack:
            # any block-opener bumps the depth, `end` decrements it above
            stripped = raw.strip()
            if stripped.endswith(" do") or stripped.endswith("do") and (
                stripped.startswith("if ") or stripped.startswith("define_method")
            ):
                depth += 1
            elif stripped.startswith("if "):
                depth += 1
            if HARDWARE_IF_RE.match(raw):
                yield os_stack[-1], raw


class HardwareGuardInvariants(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.formulae = _load_formulae()
        assert cls.formulae, f"no formulae found under {FORMULA_DIR}"

    def test_helper_finds_four_guard_lines_per_formula(self):
        """Sanity-check the extractor before the semantic tests rely on
        it. Every generated formula has exactly two Linux and two macOS
        ``if Hardware::CPU.*?`` guards; if the extractor drifts we want
        a clear failure here rather than a vacuously-passing loop below.
        """
        for name, text in self.formulae.items():
            with self.subTest(formula=name):
                guards = list(_guard_lines_by_os(text))
                by_os = {"macos": 0, "linux": 0}
                for os_name, _ in guards:
                    by_os[os_name] += 1
                self.assertEqual(
                    by_os, {"macos": 2, "linux": 2},
                    f"{name}.rb: expected 2 macOS + 2 Linux Hardware::CPU "
                    f"guards, got {by_os} (raw: {guards})",
                )

    def test_linux_platform_guards_require_is_64_bit(self):
        """Every Linux ``if Hardware::CPU.(intel|arm)?`` line must also
        gate on ``Hardware::CPU.is_64_bit?``. Without it, brew-on-Linux
        would match the 64-bit binary on 32-bit hardware (i686/armv7)
        and fail at exec time with a loader error instead of a clean
        'no bottle' message.
        """
        for name, text in self.formulae.items():
            for os_name, line in _guard_lines_by_os(text):
                if os_name != "linux":
                    continue
                with self.subTest(formula=name, line=line.strip()):
                    self.assertIn(
                        "Hardware::CPU.is_64_bit?", line,
                        f"{name}.rb: Linux guard is missing "
                        f"`Hardware::CPU.is_64_bit?`: {line.strip()!r}. "
                        f"Homebrew-on-Linux would try to install a "
                        f"64-bit binary on 32-bit hardware.",
                    )

    def test_macos_platform_guards_do_not_include_is_64_bit(self):
        """No macOS ``if Hardware::CPU.*?`` line uses ``is_64_bit?``.
        Apple dropped 32-bit userland at macOS Catalina (10.15), so the
        guard is dead code. Its presence is a strong signal that the
        file was hand-edited outside the GoReleaser codegen path — the
        edit will be clobbered on the next nightly release and mask
        whatever regression the human was trying to patch around.
        """
        for name, text in self.formulae.items():
            for os_name, line in _guard_lines_by_os(text):
                if os_name != "macos":
                    continue
                with self.subTest(formula=name, line=line.strip()):
                    self.assertNotIn(
                        "is_64_bit?", line,
                        f"{name}.rb: macOS guard carries a dead "
                        f"`is_64_bit?` clause: {line.strip()!r}. "
                        f"macOS is 64-bit only since Catalina; this "
                        f"looks like a hand-edit that diverges from "
                        f"the GoReleaser template.",
                    )


if __name__ == "__main__":
    unittest.main()
