#!/usr/bin/env python3
"""Additional invariants for the shipped Formula/*.rb files.

These invariants catch failure modes that homebrew's `brew audit` also
flags — but here they run in the tap's own unittest suite so drift
between GoReleaser-generated Formulae and the release artifacts on
GitHub is caught before the formula is tapped.

Currently asserted here:

- release-URL tag is `v<version>` and *only* that
- release tarball filename embeds `<name>_<version>_<os>_<arch>` in that
  exact order (drives `brew fetch` and the mirror manifest)
- `desc` starts with a capital letter and does NOT end with a period
  (homebrew audit rule: HomebrewAudit#audit_desc — desc must not be a
  full sentence)
- `homepage` uses https (never plain http, never a git+ssh URL)
- no leftover `bottle do` / `head do` stubs in the release-artifact
  formulae (they are pinned to a released tag; a bottle block would be
  regenerated by GoReleaser as `bottle :unneeded` on old brew versions,
  and modern brew rejects it)
"""

import re
import unittest
from pathlib import Path

FORMULA_DIR = Path(__file__).resolve().parent.parent / "Formula"

URL_LINE_RE = re.compile(r'^\s*url\s+"([^"]+)"', re.MULTILINE)
VERSION_LINE_RE = re.compile(r'^\s*version\s+"([^"]+)"', re.MULTILINE)
DESC_LINE_RE = re.compile(r'^\s*desc\s+"([^"]+)"', re.MULTILINE)
HOMEPAGE_LINE_RE = re.compile(r'^\s*homepage\s+"([^"]+)"', re.MULTILINE)

# .../releases/download/<TAG>/<FILENAME>
RELEASE_URL_RE = re.compile(
    r"/releases/download/(?P<tag>[^/]+)/(?P<file>[^/]+)$"
)

# <name>_<version>_<os>_<arch>.tar.gz
# name may itself contain hyphens (kc-agent, kubestellar-deploy, ...).
FILENAME_RE = re.compile(
    r"^(?P<name>[a-z][a-z0-9-]*[a-z0-9])"
    r"_(?P<version>[^_]+)"
    r"_(?P<os>darwin|linux)"
    r"_(?P<arch>amd64|arm64)"
    r"\.tar\.gz$"
)


class TestFormulaReleaseArtifactInvariants(unittest.TestCase):
    """Invariants tying Formula/*.rb release URLs to the artifacts they
    describe. These fail loudly whenever GoReleaser's naming template
    drifts from what the tap expects."""

    @classmethod
    def setUpClass(cls):
        cls.formulae = sorted(FORMULA_DIR.glob("*.rb"))
        assert cls.formulae, f"no formulae discovered under {FORMULA_DIR}"

    def test_every_release_url_uses_v_prefixed_tag_matching_declared_version(self):
        for f in self.formulae:
            src = f.read_text()
            m = VERSION_LINE_RE.search(src)
            self.assertIsNotNone(m, f"{f.name}: no version line")
            version = m.group(1)
            urls = URL_LINE_RE.findall(src)
            self.assertTrue(urls, f"{f.name}: no url lines")
            for url in urls:
                with self.subTest(formula=f.name, url=url):
                    rel = RELEASE_URL_RE.search(url)
                    self.assertIsNotNone(
                        rel,
                        f"{f.name}: url {url!r} is not a /releases/download/<tag>/<file> URL",
                    )
                    tag = rel.group("tag")
                    self.assertEqual(
                        tag,
                        f"v{version}",
                        f"{f.name}: release tag {tag!r} must be 'v{version}' "
                        "(GoReleaser 'v' prefix drift)",
                    )

    def test_tarball_filename_follows_name_version_os_arch_convention(self):
        for f in self.formulae:
            src = f.read_text()
            m = VERSION_LINE_RE.search(src)
            self.assertIsNotNone(m, f"{f.name}: no version line")
            version = m.group(1)
            expected_name_prefix = f.stem  # e.g. 'kc-agent'
            urls = URL_LINE_RE.findall(src)
            for url in urls:
                with self.subTest(formula=f.name, url=url):
                    rel = RELEASE_URL_RE.search(url)
                    self.assertIsNotNone(rel, f"{f.name}: not a release URL: {url!r}")
                    filename = rel.group("file")
                    parts = FILENAME_RE.match(filename)
                    self.assertIsNotNone(
                        parts,
                        f"{f.name}: tarball {filename!r} does not match "
                        "'<name>_<version>_<os>_<arch>.tar.gz'",
                    )
                    self.assertEqual(
                        parts.group("name"),
                        expected_name_prefix,
                        f"{f.name}: tarball name prefix {parts.group('name')!r} "
                        f"must equal formula stem {expected_name_prefix!r}",
                    )
                    self.assertEqual(
                        parts.group("version"),
                        version,
                        f"{f.name}: tarball version {parts.group('version')!r} "
                        f"must equal declared version {version!r}",
                    )


class TestFormulaAuditCleanMetadata(unittest.TestCase):
    """Metadata invariants that mirror `brew audit --strict` rules."""

    @classmethod
    def setUpClass(cls):
        cls.formulae = sorted(FORMULA_DIR.glob("*.rb"))

    def test_desc_starts_with_capital_letter(self):
        for f in self.formulae:
            with self.subTest(formula=f.name):
                m = DESC_LINE_RE.search(f.read_text())
                self.assertIsNotNone(m, f"{f.name}: no desc line")
                desc = m.group(1)
                self.assertTrue(
                    desc[:1].isupper(),
                    f"{f.name}: desc must start with a capital letter, "
                    f"got {desc!r}",
                )

    def test_desc_does_not_end_with_period(self):
        # `brew audit`: "Description shouldn't end with a full stop."
        for f in self.formulae:
            with self.subTest(formula=f.name):
                m = DESC_LINE_RE.search(f.read_text())
                self.assertIsNotNone(m, f"{f.name}: no desc line")
                desc = m.group(1)
                self.assertFalse(
                    desc.endswith("."),
                    f"{f.name}: desc must not end with a period, got {desc!r}",
                )

    def test_homepage_uses_https(self):
        for f in self.formulae:
            with self.subTest(formula=f.name):
                m = HOMEPAGE_LINE_RE.search(f.read_text())
                self.assertIsNotNone(m, f"{f.name}: no homepage line")
                homepage = m.group(1)
                self.assertTrue(
                    homepage.startswith("https://"),
                    f"{f.name}: homepage must use https, got {homepage!r}",
                )


class TestFormulaHasNoLeftoverStubs(unittest.TestCase):
    """These blocks are inappropriate for release-artifact formulae
    (which are pinned to a specific tag). Their presence usually means a
    stale GoReleaser template was left in place."""

    @classmethod
    def setUpClass(cls):
        cls.formulae = sorted(FORMULA_DIR.glob("*.rb"))

    def test_no_bottle_block(self):
        for f in self.formulae:
            with self.subTest(formula=f.name):
                src = f.read_text()
                self.assertNotRegex(
                    src,
                    r"^\s*bottle\s+do\b",
                    f"{f.name}: stray `bottle do` block; homebrew rejects "
                    "bottles on tap formulae unless the bottle blocks are "
                    "explicitly maintained.",
                )

    def test_no_head_block(self):
        # head "<url>" or head do
        for f in self.formulae:
            with self.subTest(formula=f.name):
                src = f.read_text()
                self.assertNotRegex(
                    src,
                    r"^\s*head\b",
                    f"{f.name}: stray `head` declaration; these formulae "
                    "are pinned to a released tag and must not offer HEAD.",
                )


if __name__ == "__main__":
    unittest.main()
