"""Preamble-block invariants for every ``Formula/*.rb``.

Existing tests already assert:

* the first two non-blank lines are ``# typed: false`` and
  ``# frozen_string_literal: true`` (``test_magic_comments_lead_every_formula``);
* the file contains the ``This file was generated by GoReleaser. DO NOT
  EDIT.`` marker somewhere (``test_every_formula_carries_the_do_not_edit_marker``);
* there is exactly one ``class ... < Formula`` header
  (``test_class_name_matches_filename_and_extends_formula``).

None of them lock the **relative position** of the three preamble pieces
to each other.  A codegen bug or hand-edit could:

* move the ``DO NOT EDIT`` marker to the tail of the file, or into a
  method body — no test would notice, and downstream reviewers looking
  at the header wouldn't see the "do not touch" warning;
* insert extra prose between the magic comments and the class body,
  which changes what tooling like ``brew audit --new-formula`` sees and
  can subtly break Sorbet's file-scoped analysis;
* drop the blank line between the magic comments and the marker,
  which changes rubocop's expectation and would rewrite the file on
  next lint.

The invariants below lock the preamble as a fixed 3-line block plus a
following blank plus the ``class`` header — the exact shape GoReleaser
emits and the only shape that survives ``brew audit`` clean.
"""
from __future__ import annotations

import pathlib
import re
import unittest


REPO_ROOT = pathlib.Path(__file__).resolve().parents[1]
FORMULA_DIR = REPO_ROOT / "Formula"

DO_NOT_EDIT_RE = re.compile(
    r"^#\s*This file was generated by GoReleaser\.\s*DO NOT EDIT\.\s*$",
)
CLASS_HEADER_RE = re.compile(r"^class\s+\w+\s*<\s*Formula\s*$")
MAGIC_TYPED_RE = re.compile(r"^#\s*typed:\s*false\s*$")
MAGIC_FROZEN_RE = re.compile(r"^#\s*frozen_string_literal:\s*true\s*$")


class FormulaPreambleBlockInvariants(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.formulae = {
            p.stem: p.read_text(encoding="utf-8")
            for p in sorted(FORMULA_DIR.glob("*.rb"))
        }
        assert cls.formulae, f"no formulae under {FORMULA_DIR}"

    def _non_blank_lines(self, text: str) -> list[tuple[int, str]]:
        """Return ``(1-based line number, stripped content)`` for every
        non-blank line, in file order."""
        return [
            (i + 1, ln.rstrip())
            for i, ln in enumerate(text.splitlines())
            if ln.strip()
        ]

    # ------------------------------------------------------------------
    # Real formulae
    # ------------------------------------------------------------------

    def test_do_not_edit_marker_is_third_non_blank_line(self):
        # The magic comments occupy positions 1-2; the DO NOT EDIT
        # marker must occupy position 3 so the warning is impossible to
        # miss when a reviewer opens the file.  If it drifts anywhere
        # else, the file may still ship but the marker's purpose is
        # lost.
        for name, text in self.formulae.items():
            with self.subTest(formula=name):
                nb = self._non_blank_lines(text)
                self.assertGreaterEqual(
                    len(nb), 3,
                    f"{name}.rb has fewer than three non-blank lines",
                )
                self.assertRegex(
                    nb[2][1], DO_NOT_EDIT_RE,
                    f"{name}.rb: 3rd non-blank line is "
                    f"{nb[2][1]!r} (line {nb[2][0]}), expected the "
                    f"GoReleaser DO NOT EDIT marker",
                )

    def test_class_header_is_fourth_non_blank_line(self):
        # The class header must be the very next non-blank line after
        # the marker.  If codegen or a hand-edit inserted an extra
        # comment or `require '...'` line between them, downstream
        # tooling would still work but ``brew audit --new-formula``
        # would emit a "non-empty top of file" warning and future
        # rubocop autofixes could rewrite the file in place.
        for name, text in self.formulae.items():
            with self.subTest(formula=name):
                nb = self._non_blank_lines(text)
                self.assertGreaterEqual(
                    len(nb), 4,
                    f"{name}.rb has fewer than four non-blank lines",
                )
                self.assertRegex(
                    nb[3][1], CLASS_HEADER_RE,
                    f"{name}.rb: 4th non-blank line is "
                    f"{nb[3][1]!r} (line {nb[3][0]}), expected the "
                    f"`class <Name> < Formula` header",
                )

    def test_do_not_edit_marker_appears_exactly_once(self):
        # An unintended second copy of the DO NOT EDIT marker (e.g.
        # from a copy-paste inside a method body) creates ambiguity for
        # tooling that scans for it — most notably review bots that
        # flag human edits to generated files.  Guard against
        # duplicates.
        for name, text in self.formulae.items():
            with self.subTest(formula=name):
                count = sum(
                    1 for ln in text.splitlines()
                    if DO_NOT_EDIT_RE.match(ln.rstrip())
                )
                self.assertEqual(
                    count, 1,
                    f"{name}.rb: DO NOT EDIT marker appears {count} "
                    f"times, want exactly 1",
                )

    def test_blank_line_separates_magic_comments_from_marker(self):
        # GoReleaser emits: magic comments, blank, marker, class.  The
        # blank line is load-bearing for rubocop's Layout/EmptyLines
        # cop; if it disappears the next lint pass will re-insert it
        # and rewrite the file.  Test on the raw file so a hidden
        # trailing-whitespace character on the "blank" line is
        # caught too.
        for name, text in self.formulae.items():
            with self.subTest(formula=name):
                lines = text.splitlines()
                # The magic comments MUST be at raw lines 1 and 2
                # (the pre-existing invariant only asserted the first
                # two *non-blank* lines match).  Assert the raw
                # positions too so a stray blank in front of them is
                # caught.
                self.assertGreaterEqual(len(lines), 5)
                self.assertRegex(
                    lines[0], MAGIC_TYPED_RE,
                    f"{name}.rb line 1: got {lines[0]!r}, want "
                    f"`# typed: false`",
                )
                self.assertRegex(
                    lines[1], MAGIC_FROZEN_RE,
                    f"{name}.rb line 2: got {lines[1]!r}, want "
                    f"`# frozen_string_literal: true`",
                )
                self.assertEqual(
                    lines[2], "",
                    f"{name}.rb line 3 must be a truly empty line "
                    f"(no whitespace) separating magic comments from "
                    f"the DO NOT EDIT marker; got {lines[2]!r}",
                )
                self.assertRegex(
                    lines[3], DO_NOT_EDIT_RE,
                    f"{name}.rb line 4: got {lines[3]!r}, want the "
                    f"DO NOT EDIT marker",
                )
                self.assertRegex(
                    lines[4], CLASS_HEADER_RE,
                    f"{name}.rb line 5: got {lines[4]!r}, want the "
                    f"`class <Name> < Formula` header (no blank "
                    f"between marker and class body)",
                )

    # ------------------------------------------------------------------
    # Regex self-tests — a mis-authored guard is worse than none.
    # ------------------------------------------------------------------

    def test_do_not_edit_regex_matches_the_canonical_form(self):
        self.assertRegex(
            "# This file was generated by GoReleaser. DO NOT EDIT.",
            DO_NOT_EDIT_RE,
        )
        # Reject unrelated marker prose.
        self.assertNotRegex(
            "# Do not edit — hand-maintained.", DO_NOT_EDIT_RE,
        )

    def test_class_header_regex_rejects_wrong_parent(self):
        self.assertRegex("class KcAgent < Formula", CLASS_HEADER_RE)
        # Common bug: someone renames the parent class or drops it.
        self.assertNotRegex("class KcAgent < Cask", CLASS_HEADER_RE)
        self.assertNotRegex("class KcAgent", CLASS_HEADER_RE)


if __name__ == "__main__":  # pragma: no cover
    unittest.main()
