name: "PR Title Verifier"

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

permissions: read-all  # default read; writes scoped to job below

jobs:
  verify:
    permissions:
      contents: read
      pull-requests: write
    uses: kubestellar/infra/.github/workflows/reusable-pr-verify-title.yml@af322d48cc67ade7345cabc6a0ed55c6c7040ee4  # main
